### ISSUE TITLE
Support SSL

### ISSUE THREAD

**Issue by marcinkoziej** [hassansin/amqptools#1]
Hi!

After checking some cli amqp tools out there, amqptools seems most solid. However, it would be great if it could also support amqp over SSL! (amqps). Would that be possible to add? 

It looks like the go amqp library supports just passing the `amqps;//` url to enable basic SSL mode (without client/server cert validation). 
Still this is better then sending plaintext.

**Comment by hassansin** [comment]
Thanks for your PR.
